// flow-typed signature: 731e85444cb5993b59a5bdd777ac8063
// flow-typed version: <<STUB>>/aplay_v^1.2.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aplay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aplay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aplay/node-aplay' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aplay/node-aplay.js' {
  declare module.exports: $Exports<'aplay/node-aplay'>;
}
