// flow-typed signature: 59ebd44a7f47d3e1a2304e7002e37b10
// flow-typed version: <<STUB>>/node-nfcpy-id_v^0.1.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-nfcpy-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-nfcpy-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-nfcpy-id/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-nfcpy-id/lib/index.js' {
  declare module.exports: $Exports<'node-nfcpy-id/lib/index'>;
}
